package model;
// Generated 8 ene 2024 17:43:18 by Hibernate Tools 6.3.1.Final

/**
 * ColeccionId generated by hbm2java
 */
public class ColeccionId implements java.io.Serializable {

	private int idJuego;
	private int idUsuario;

	public ColeccionId() {
	}

	public ColeccionId(int idJuego, int idUsuario) {
		this.idJuego = idJuego;
		this.idUsuario = idUsuario;
	}

	public int getIdJuego() {
		return this.idJuego;
	}

	public void setIdJuego(int idJuego) {
		this.idJuego = idJuego;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ColeccionId))
			return false;
		ColeccionId castOther = (ColeccionId) other;

		return (this.getIdJuego() == castOther.getIdJuego()) && (this.getIdUsuario() == castOther.getIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdJuego();
		result = 37 * result + this.getIdUsuario();
		return result;
	}

}
