package model;
// Generated 8 ene 2024 17:43:18 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String email;
	private Set coleccions = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(String username, String password, String email, Set coleccions) {
		this.username = username;
		this.password = password;
		this.email = email;
		this.coleccions = coleccions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getColeccions() {
		return this.coleccions;
	}

	public void setColeccions(Set coleccions) {
		this.coleccions = coleccions;
	}

}
