/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import controlador.HibernateUtil;
import java.awt.Color;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Usuarios;
import model.Videojuegos;
import org.hibernate.PropertyValueException;

/**
 *
 * @author Javier Marcos Cobaleda
 */
public class PanelRegistrar extends javax.swing.JPanel {
    private Usuarios usuario;
    /**
     * Creates new form PanelRegistrar
     */
    public PanelRegistrar(Usuarios usuario) {
        initComponents();
        /**
         * recibir el usuario de la ventanaPrincipal
         */
        this.usuario=usuario;
        /**
         * Modificaciones esteticas de los elementos graficos
         */
        lblRegistrar.setForeground(Color.BLACK);
        btnAgregarDeseos.setForeground(Color.BLACK);
        btnAgregarColeccion.setForeground(Color.BLACK);
        tfFecha.putClientProperty( FlatClientProperties.TEXT_FIELD_LEADING_ICON,new FlatSVGIcon( "img/calendario.svg" ) );
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelFondo = new javax.swing.JPanel();
        panelRound1 = new vista.PanelRound();
        lblRegistrar = new javax.swing.JLabel();
        lbltitulo = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        lblplataforma = new javax.swing.JLabel();
        tfGenero = new javax.swing.JTextField();
        lblgenero1 = new javax.swing.JLabel();
        rbPlayStation = new javax.swing.JRadioButton();
        rbNintendo = new javax.swing.JRadioButton();
        rbXbox = new javax.swing.JRadioButton();
        rbPc = new javax.swing.JRadioButton();
        lblconsola = new javax.swing.JLabel();
        jcbConsola = new javax.swing.JComboBox<>();
        lblfecha = new javax.swing.JLabel();
        tfFecha = new javax.swing.JTextField();
        lblgenero4 = new javax.swing.JLabel();
        tfEdicion = new javax.swing.JTextField();
        lblgenero5 = new javax.swing.JLabel();
        jsValoracion = new javax.swing.JSlider();
        estrellas = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnAgregarDeseos = new javax.swing.JButton();
        btnAgregarColeccion = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(950, 810));

        panelFondo.setBackground(new java.awt.Color(30, 30, 30));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(234, 164, 28));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegistrar.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblRegistrar.setText("REGISTRAR JUEGO");
        panelRound1.add(lblRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        panelFondo.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 519, 113));

        lbltitulo.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbltitulo.setText("Título");
        panelFondo.add(lbltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        tfTitulo.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        tfTitulo.setForeground(new java.awt.Color(255, 255, 255));
        tfTitulo.setToolTipText("Introduce el título del juego a registrar");
        tfTitulo.setMargin(new java.awt.Insets(2, 12, 2, 6));
        tfTitulo.setPreferredSize(new java.awt.Dimension(221, 22));
        tfTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfTituloMouseClicked(evt);
            }
        });
        panelFondo.add(tfTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 390, 30));

        lblplataforma.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        lblplataforma.setForeground(new java.awt.Color(255, 255, 255));
        lblplataforma.setText("Plataforma");
        panelFondo.add(lblplataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        tfGenero.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        tfGenero.setForeground(new java.awt.Color(255, 255, 255));
        tfGenero.setToolTipText("Introduce el género al que pertene el juego");
        tfGenero.setMargin(new java.awt.Insets(2, 12, 2, 6));
        tfGenero.setPreferredSize(new java.awt.Dimension(221, 22));
        tfGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfGeneroMouseClicked(evt);
            }
        });
        panelFondo.add(tfGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 390, 30));

        lblgenero1.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        lblgenero1.setForeground(new java.awt.Color(255, 255, 255));
        lblgenero1.setText("Género");
        panelFondo.add(lblgenero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        buttonGroup1.add(rbPlayStation);
        rbPlayStation.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        rbPlayStation.setForeground(new java.awt.Color(255, 255, 255));
        rbPlayStation.setText("PlayStation");
        rbPlayStation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbPlayStation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbPlayStationMouseClicked(evt);
            }
        });
        rbPlayStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPlayStationActionPerformed(evt);
            }
        });
        panelFondo.add(rbPlayStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));

        buttonGroup1.add(rbNintendo);
        rbNintendo.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        rbNintendo.setForeground(new java.awt.Color(255, 255, 255));
        rbNintendo.setText("Nintendo");
        rbNintendo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbNintendo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbNintendoMouseClicked(evt);
            }
        });
        rbNintendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNintendoActionPerformed(evt);
            }
        });
        panelFondo.add(rbNintendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        buttonGroup1.add(rbXbox);
        rbXbox.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        rbXbox.setForeground(new java.awt.Color(255, 255, 255));
        rbXbox.setText("Xbox");
        rbXbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbXbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbXboxMouseClicked(evt);
            }
        });
        rbXbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbXboxActionPerformed(evt);
            }
        });
        panelFondo.add(rbXbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        buttonGroup1.add(rbPc);
        rbPc.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        rbPc.setForeground(new java.awt.Color(255, 255, 255));
        rbPc.setText("PC");
        rbPc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbPc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbPcMouseClicked(evt);
            }
        });
        rbPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPcActionPerformed(evt);
            }
        });
        panelFondo.add(rbPc, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));

        lblconsola.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        lblconsola.setForeground(new java.awt.Color(255, 255, 255));
        lblconsola.setText("Consola");
        panelFondo.add(lblconsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        jcbConsola.setToolTipText("Selecciona la consola a la que pertene el juego");
        jcbConsola.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbConsola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbConsolaMouseClicked(evt);
            }
        });
        panelFondo.add(jcbConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 390, 30));

        lblfecha.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        lblfecha.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha.setText("<html><p>Fecha</p><p>de salida</p></html>");
        panelFondo.add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        tfFecha.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        tfFecha.setForeground(new java.awt.Color(153, 153, 153));
        tfFecha.setText("dd/MM/aaaa");
        tfFecha.setToolTipText("Añade aquí la fecha de lanzamiento con formato <dd/MM/aaaa> del juego que deseas registrar");
        tfFecha.setMargin(new java.awt.Insets(2, 12, 2, 6));
        tfFecha.setPreferredSize(new java.awt.Dimension(221, 22));
        tfFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfFechaMouseClicked(evt);
            }
        });
        panelFondo.add(tfFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 390, 30));

        lblgenero4.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        lblgenero4.setForeground(new java.awt.Color(255, 255, 255));
        lblgenero4.setText("Valoración");
        panelFondo.add(lblgenero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, -1));

        tfEdicion.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        tfEdicion.setForeground(new java.awt.Color(255, 255, 255));
        tfEdicion.setToolTipText("Inserta aquí la tipo de edición del juego que deseas registrar");
        tfEdicion.setMargin(new java.awt.Insets(2, 12, 2, 6));
        tfEdicion.setPreferredSize(new java.awt.Dimension(221, 22));
        tfEdicion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfEdicionMouseClicked(evt);
            }
        });
        panelFondo.add(tfEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 390, 30));

        lblgenero5.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        lblgenero5.setForeground(new java.awt.Color(255, 255, 255));
        lblgenero5.setText("Edición");
        panelFondo.add(lblgenero5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, -1, -1));

        jsValoracion.setMaximum(4);
        jsValoracion.setToolTipText("Puntúa el juego de 1 a 5 estrellas");
        jsValoracion.setValue(2);
        jsValoracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsValoracion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsValoracionStateChanged(evt);
            }
        });
        jsValoracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsValoracionMouseClicked(evt);
            }
        });
        panelFondo.add(jsValoracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 530, -1));

        estrellas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3estrellas.png"))); // NOI18N
        panelFondo.add(estrellas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(234, 164, 28));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setToolTipText("Vacía todos los campos de texto");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panelFondo.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 650, 134, 50));

        btnAgregarDeseos.setBackground(new java.awt.Color(234, 164, 28));
        btnAgregarDeseos.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        btnAgregarDeseos.setText("<html><center>AGREGAR A<br>LISTA DE DESEOS</center></html>");
        btnAgregarDeseos.setToolTipText("Registra un juego en la base de datos y los agrega a tu lista de deseos");
        btnAgregarDeseos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarDeseos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarDeseos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDeseosActionPerformed(evt);
            }
        });
        panelFondo.add(btnAgregarDeseos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, 134, 50));

        btnAgregarColeccion.setBackground(new java.awt.Color(234, 164, 28));
        btnAgregarColeccion.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        btnAgregarColeccion.setText("<html><center>AGREGAR A<br>MI COLECCIÓN</center></html>");
        btnAgregarColeccion.setToolTipText("Registra un juego en la base de datos y lo añade a tu colección");
        btnAgregarColeccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarColeccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarColeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarColeccionActionPerformed(evt);
            }
        });
        panelFondo.add(btnAgregarColeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 650, 134, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Método para rellenar el combobox al clickar en el radioButton PlayStation
     * @param evt 
     */
    private void rbPlayStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPlayStationActionPerformed
        /**
         * Vaciar la lista del comboBox
         */
        jcbConsola.removeAllItems();
        /**
         * Rellenar la lista del comboBox
         */
        jcbConsola.addItem("PS 5");
        jcbConsola.addItem("PS 4");
        jcbConsola.addItem("PS 3");
        jcbConsola.addItem("PS 2");
        jcbConsola.addItem("PlayStation");
        jcbConsola.addItem("PS Vita");
        jcbConsola.addItem("PSP");
    }//GEN-LAST:event_rbPlayStationActionPerformed
    /**
     * Método para rellenar el combobox al clickar en el radioButton Nintendo
     * @param evt 
     */
    private void rbNintendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNintendoActionPerformed
        /**
         * Vaciar la lista del comboBox
         */
        jcbConsola.removeAllItems();
        /**
         * Rellenar la lista del comboBox
         */
        jcbConsola.addItem("Switch");
        jcbConsola.addItem("Wii U");
        jcbConsola.addItem("Wii");
        jcbConsola.addItem("GameCube");
        jcbConsola.addItem("Nintendo 64");
        jcbConsola.addItem("Supernintendo");
        jcbConsola.addItem("NES");
        jcbConsola.addItem("DS/3ds");
        jcbConsola.addItem("GBA");
        jcbConsola.addItem("GBColor");
        jcbConsola.addItem("GameBoy");
    }//GEN-LAST:event_rbNintendoActionPerformed
    /**
     * Método para rellenar el combobox al clickar en el radioButton XBox
     * @param evt 
     */
    private void rbXboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbXboxActionPerformed
        /**
         * Vaciar la lista del comboBox
         */
        jcbConsola.removeAllItems();
        /**
         * Rellenar la lista del comboBox
         */
        jcbConsola.addItem("Xbox series X-S");
        jcbConsola.addItem("Xbox one");
        jcbConsola.addItem("Xbox 360");
        jcbConsola.addItem("Xbox");    
    }//GEN-LAST:event_rbXboxActionPerformed
    /**
     * Método para rellenar el combobox al clickar en el radioButton PC
     * @param evt 
     */
    private void rbPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPcActionPerformed
        /**
         * Vaciar la lista del comboBox
         */
        jcbConsola.removeAllItems();
        /**
         * Rellenar la lista del comboBox
         */
        jcbConsola.addItem("Steam");
        jcbConsola.addItem("Epic Games");
        jcbConsola.addItem("Origin");
        jcbConsola.addItem("Ubisoft");
        jcbConsola.addItem("Otros");
    }//GEN-LAST:event_rbPcActionPerformed
    /**
     * Método de funcionalidad del botón limpiar
     * @param evt 
     */
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        /**
         * Llamamos al método limpiar
         */
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed
    /**
     * Método de funcionalidad del botón deseos
     * @param evt 
     */
    private void btnAgregarDeseosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDeseosActionPerformed
        boolean correcto=true;
        /**
         * Gestionamos el control de errores evitando campos vacíos en los textfields
         */
        try{
            Videojuegos v=new Videojuegos();
            if (tfTitulo.getText().equals("")){
                JOptionPane.showMessageDialog(null, "ERROR, Introduzca el título","Error", JOptionPane.ERROR_MESSAGE);
            } else if (tfGenero.getText().equals("")){
                JOptionPane.showMessageDialog(null, "ERROR, Introduzca el género","Error", JOptionPane.ERROR_MESSAGE);
            } else if (tfFecha.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ERROR, Formato de fecha incorrecto","Error", JOptionPane.ERROR_MESSAGE);
            } else if (tfEdicion.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ERROR, Introduzca la edición","Error", JOptionPane.ERROR_MESSAGE);
            } else if(!rbNintendo.isSelected() && !rbPlayStation.isSelected() && !rbXbox.isSelected() && !rbPc.isSelected()){
                JOptionPane.showMessageDialog(null, "ERROR, Seleccione una plataforma","Error", JOptionPane.ERROR_MESSAGE);
            } else if(jcbConsola.getSelectedItem()==null){
                JOptionPane.showMessageDialog(null, "ERROR, Seleccione una consola","Error", JOptionPane.ERROR_MESSAGE);
            } else {
           
                v.setTitulo(tfTitulo.getText());
                v.setGenero(tfGenero.getText());

                /**
                 * Parsear la fecha si el campo no está vacío
                 */
                if(!tfFecha.getText().isEmpty()){
                    SimpleDateFormat fecha=new SimpleDateFormat("dd/MM/yyyy");
                    try {
                        //v.setFechaSalida((Date) fecha.parse(tfFecha.getText()));
                        java.util.Date utilDate = fecha.parse(tfFecha.getText());
                        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                        v.setFechaSalida(sqlDate);
                    } catch (ParseException ex) {
                        Logger.getLogger(PanelRegistrar.class.getName()).log(Level.SEVERE, null, ex);
                        //System.err.println("Error de formato fecha");
                        JOptionPane.showMessageDialog(null, "ERROR, Formato de fecha incorrecto <dd/MM/yyyy>","Error", JOptionPane.ERROR_MESSAGE);
                        /**
                         * ponemos la bandera a false para evitar la inserción de un formato de fecha incorrecto
                         */
                        correcto=false;
                    }
                }
                v.setEdicion(tfEdicion.getText());
                /**
                 * Obetener la plataforma y la consola
                 */
                if(rbNintendo.isSelected()){
                    v.setPlataforma("Nintendo");
                    String consola=(String)jcbConsola.getSelectedItem();
                    v.setConsola(consola);
                }else if(rbPlayStation.isSelected()){
                    v.setPlataforma("PlayStation");
                    String consola=(String)jcbConsola.getSelectedItem();
                    v.setConsola(consola);
                }else if(rbXbox.isSelected()){
                    v.setPlataforma("XBox");
                    String consola=(String)jcbConsola.getSelectedItem();
                    v.setConsola(consola);
                }
                else if(rbPc.isSelected()){
                    v.setPlataforma("PC");
                    String consola=(String)jcbConsola.getSelectedItem();
                    v.setConsola(consola);
                }

                v.setValoracion(jsValoracion.getValue());
                /**
                 * Si todo es correcto registramos el juego y lo insertamos en la lista de deseos del usuario
                 */
                if(correcto){
                    /**
                     * Llamamos al método insertarListaDeseos
                     */
                    if(HibernateUtil.insertarListaDeseos(v,usuario)){
                        JOptionPane.showMessageDialog(null, "Videojuego insertado correctamente en la lista de deseos");
                        /**
                         * Llamamos al método limpiar para resetear los textFields
                         */
                        limpiar();
                    }else{
                        JOptionPane.showMessageDialog(null, "ERROR,no se ha podido añadir el videojuego a su lista de deseos","Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }catch(PropertyValueException e){
            JOptionPane.showMessageDialog(null, "ERROR,no se ha podido añadir el videojuego a su lista de deseos","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarDeseosActionPerformed
    /**
     * Método de funcionalidad del botón agregar colección
     * @param evt 
     */
    private void btnAgregarColeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarColeccionActionPerformed
        boolean correcto=true;
        /**
         * Gestionamos el control de errores evitando campos vacíos en los textfields
         */
        try{
            Videojuegos v=new Videojuegos();
            if (tfTitulo.getText().equals("")){
                JOptionPane.showMessageDialog(null, "ERROR, Introduzca el título","Error", JOptionPane.ERROR_MESSAGE);
            } else if (tfGenero.getText().equals("")){
                JOptionPane.showMessageDialog(null, "ERROR, Introduzca el género","Error", JOptionPane.ERROR_MESSAGE);
            } else if (tfFecha.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ERROR, Formato de fecha incorrecto","Error", JOptionPane.ERROR_MESSAGE);
            } else if (tfEdicion.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ERROR, Introduzca la edición","Error", JOptionPane.ERROR_MESSAGE);
            } else if(!rbNintendo.isSelected() && !rbPlayStation.isSelected() && !rbXbox.isSelected() && !rbPc.isSelected()){
                JOptionPane.showMessageDialog(null, "ERROR, Seleccione una plataforma","Error", JOptionPane.ERROR_MESSAGE);
            } else if(jcbConsola.getSelectedItem()==null){
                JOptionPane.showMessageDialog(null, "ERROR, Seleccione una consola","Error", JOptionPane.ERROR_MESSAGE);
            } else {
           
                v.setTitulo(tfTitulo.getText());
                v.setGenero(tfGenero.getText());

                /**
                 * Parsear la fecha si el campo no está vacío
                 */
                if(!tfFecha.getText().isEmpty()){
                    SimpleDateFormat fecha=new SimpleDateFormat("dd/MM/yyyy");
                    try {
                        //v.setFechaSalida((Date) fecha.parse(tfFecha.getText()));
                        java.util.Date utilDate = fecha.parse(tfFecha.getText());
                        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                        v.setFechaSalida(sqlDate);
                    } catch (ParseException ex) {
                        Logger.getLogger(PanelRegistrar.class.getName()).log(Level.SEVERE, null, ex);
                        //System.err.println("Error de formato fecha");
                        JOptionPane.showMessageDialog(null, "ERROR, Formato de fecha incorrecto <dd/MM/yyyy>","Error", JOptionPane.ERROR_MESSAGE);
                        /**
                         * ponemos la bandera a false para evitar la inserción de un formato de fecha incorrecto
                         */
                        correcto=false;
                    }
                }
                v.setEdicion(tfEdicion.getText());
                /**
                 * Obetener la plataforma y la consola
                 */
                if(rbNintendo.isSelected()){
                    v.setPlataforma("Nintendo");
                    String consola=(String)jcbConsola.getSelectedItem();
                    v.setConsola(consola);
                }else if(rbPlayStation.isSelected()){
                    v.setPlataforma("PlayStation");
                    String consola=(String)jcbConsola.getSelectedItem();
                    v.setConsola(consola);
                }else if(rbXbox.isSelected()){
                    v.setPlataforma("XBox");
                    String consola=(String)jcbConsola.getSelectedItem();
                    v.setConsola(consola);
                }
                else if(rbPc.isSelected()){
                    v.setPlataforma("PC");
                    String consola=(String)jcbConsola.getSelectedItem();
                    v.setConsola(consola);
                }

                v.setValoracion(jsValoracion.getValue());
                /**
                 * Si todo es correcto registramos el juego y lo insertamos en la colección del usuario
                 */
                if(correcto){
                    /**
                     * Llamamos al método insertarColección
                     */
                    if(HibernateUtil.insertarColeccion(v,usuario)){
                        JOptionPane.showMessageDialog(null, "Videojuego insertado correctamente en la colección");
                        limpiar();
                    }else{
                        JOptionPane.showMessageDialog(null, "ERROR,no se ha podido añadir el videojuego a su colección","Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }catch(PropertyValueException e){
            JOptionPane.showMessageDialog(null, "ERROR,no se ha podido añadir el videojuego a su colección","Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnAgregarColeccionActionPerformed
    /**
     * Método para rellenar las estrellas a partir del slider
     * @param evt 
     */
    private void jsValoracionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsValoracionStateChanged
        /**
         * Rellenar las estrellas en funcion de la valoracion
         */
        switch(jsValoracion.getValue()){
            case 0:
                estrellas.setIcon(new ImageIcon("src/main/java/img/1estrella.png"));
                break;
            case 1:
                estrellas.setIcon(new ImageIcon("src/main/java/img/2estrellas.png"));
                break;
            case 2:
                estrellas.setIcon(new ImageIcon("src/main/java/img/3estrellas.png"));
                break;
            case 3:
                estrellas.setIcon(new ImageIcon("src/main/java/img/4estrellas.png"));
                break;
            case 4:
                estrellas.setIcon(new ImageIcon("src/main/java/img/5estrellas.png"));
                break;               
        }
    }//GEN-LAST:event_jsValoracionStateChanged
    /**
     * Método para vaciar el texto de la Fecha al clickar en ella
     * @param evt 
     */
    private void tfFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfFechaMouseClicked
        if(tfFecha.getText().equals("dd/MM/aaaa")){
            tfFecha.setText("");
            tfFecha.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_tfFechaMouseClicked
    /**
     * Método para rellenar el texto de la Fecha al clickar en consola
     * @param evt 
     */
    private void jcbConsolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbConsolaMouseClicked
        //Si la fecha está vacía rellenarla por defecto
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jcbConsolaMouseClicked
    /**
     * Método para rellenar el texto de la Fecha al clickar en edicion
     * @param evt 
     */
    private void tfEdicionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEdicionMouseClicked
        //Si la fecha está vacía rellenarla por defecto
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tfEdicionMouseClicked
    /**
     * Método para rellenar el texto de la Fecha al clickar en genero
     * @param evt 
     */
    private void tfGeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfGeneroMouseClicked
        //Si la fecha está vacía rellenarla por defecto
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tfGeneroMouseClicked
    /**
     * Método para rellenar el texto de la Fecha al clickar en titulo
     * @param evt 
     */
    private void tfTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTituloMouseClicked
        //Si la fecha está vacía rellenarla por defecto
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tfTituloMouseClicked
    /**
     * Método para rellenar el texto de la Fecha al clickar en valoración
     * @param evt 
     */
    private void jsValoracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsValoracionMouseClicked
        //Si la fecha está vacía rellenarla por defecto
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jsValoracionMouseClicked
    /**
     * Método para rellenar el texto de la Fecha al clickar en Nintendo
     * @param evt 
     */
    private void rbNintendoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbNintendoMouseClicked
        //Si la fecha está vacía rellenarla por defecto
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_rbNintendoMouseClicked
    /**
     * Método para rellenar el texto de la Fecha al clickar en PlayStation
     * @param evt 
     */
    private void rbPlayStationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbPlayStationMouseClicked
        //Si la fecha está vacía rellenarla por defecto
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_rbPlayStationMouseClicked
    /**
     * Método para rellenar el texto de la Fecha al clickar en XBox
     * @param evt 
     */
    private void rbXboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbXboxMouseClicked
        //Si la fecha está vacía rellenarla por defecto
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_rbXboxMouseClicked
    /**
     * Método para rellenar el texto de la Fecha al clickar en PC
     * @param evt 
     */
    private void rbPcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbPcMouseClicked
        //Si la fecha está vacía rellenarla por defecto
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_rbPcMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarColeccion;
    private javax.swing.JButton btnAgregarDeseos;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel estrellas;
    private javax.swing.JComboBox<String> jcbConsola;
    private javax.swing.JSlider jsValoracion;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblconsola;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblgenero1;
    private javax.swing.JLabel lblgenero4;
    private javax.swing.JLabel lblgenero5;
    private javax.swing.JLabel lblplataforma;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPanel panelFondo;
    private vista.PanelRound panelRound1;
    private javax.swing.JRadioButton rbNintendo;
    private javax.swing.JRadioButton rbPc;
    private javax.swing.JRadioButton rbPlayStation;
    private javax.swing.JRadioButton rbXbox;
    private javax.swing.JTextField tfEdicion;
    private javax.swing.JTextField tfFecha;
    private javax.swing.JTextField tfGenero;
    private javax.swing.JTextField tfTitulo;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Método que resetea los textfields
     */
    public void limpiar(){
        /**
         * Vaciar todos los campos
         */
        tfTitulo.setText("");
        tfGenero.setText("");
        tfFecha.setText("dd/MM/aaaa");
        tfFecha.setForeground(new Color(153,153,153));
        tfEdicion.setText("");
        rbNintendo.setSelected(false);
        rbPlayStation.setSelected(false);
        rbXbox.setSelected(false);
        rbPc.setSelected(false);
        jsValoracion.setValue(2);
    }
}