/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import controlador.HibernateUtil;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Usuarios;
import model.Videojuegos;
import org.hibernate.PropertyValueException;

/**
 *
 * @author Javier Marcos Cobaleda
 */
public class PanelGestionar extends javax.swing.JPanel {
    private Usuarios usuario;
    int idJuego=0;
    /**
     * Creates new form PanelGestionar
     */
    public PanelGestionar(Usuarios usuario) {
        initComponents();
        /**
         * recibir el usuario de la ventanaPrincipal
         */
        this.usuario=usuario;
        /**
         * Modificaciones esteticas de los elementos graficos
         */
        lblGestionar.setForeground(Color.BLACK);
        btnModificar.setForeground(Color.BLACK);
        btnEliminar.setForeground(Color.BLACK);
        tfFecha.putClientProperty( FlatClientProperties.TEXT_FIELD_LEADING_ICON,new FlatSVGIcon( "img/calendario.svg" ) );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelFondo = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        lblplataforma = new javax.swing.JLabel();
        tfGenero = new javax.swing.JTextField();
        lblgenero1 = new javax.swing.JLabel();
        rbPlayStation = new javax.swing.JRadioButton();
        rbNintendo = new javax.swing.JRadioButton();
        rbXbox = new javax.swing.JRadioButton();
        rbPc = new javax.swing.JRadioButton();
        lblconsola = new javax.swing.JLabel();
        jcbConsola = new javax.swing.JComboBox<>();
        lblfecha = new javax.swing.JLabel();
        tfFecha = new javax.swing.JTextField();
        lblgenero4 = new javax.swing.JLabel();
        tfEdicion = new javax.swing.JTextField();
        lblgenero5 = new javax.swing.JLabel();
        jsValoracion = new javax.swing.JSlider();
        estrellas = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        panelRound1 = new vista.PanelRound();
        lblGestionar = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbltitulo2 = new javax.swing.JLabel();

        panelFondo.setBackground(new java.awt.Color(30, 30, 30));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitulo.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(234, 164, 28));
        lbltitulo.setText("DATOS NUEVOS");
        panelFondo.add(lbltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        tfTitulo.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        tfTitulo.setForeground(new java.awt.Color(255, 255, 255));
        tfTitulo.setToolTipText("Introduce el nuevo título");
        tfTitulo.setPreferredSize(new java.awt.Dimension(221, 22));
        tfTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfTituloMouseClicked(evt);
            }
        });
        panelFondo.add(tfTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 390, 30));

        lblplataforma.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        lblplataforma.setForeground(new java.awt.Color(255, 255, 255));
        lblplataforma.setText("Plataforma");
        panelFondo.add(lblplataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        tfGenero.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        tfGenero.setForeground(new java.awt.Color(255, 255, 255));
        tfGenero.setToolTipText("Introduce el nuevo género");
        tfGenero.setPreferredSize(new java.awt.Dimension(221, 22));
        tfGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfGeneroMouseClicked(evt);
            }
        });
        panelFondo.add(tfGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 390, 30));

        lblgenero1.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        lblgenero1.setForeground(new java.awt.Color(255, 255, 255));
        lblgenero1.setText("Género");
        panelFondo.add(lblgenero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        buttonGroup1.add(rbPlayStation);
        rbPlayStation.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        rbPlayStation.setForeground(new java.awt.Color(255, 255, 255));
        rbPlayStation.setText("PlayStation");
        rbPlayStation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbPlayStation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbPlayStationMouseClicked(evt);
            }
        });
        rbPlayStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPlayStationActionPerformed(evt);
            }
        });
        panelFondo.add(rbPlayStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        buttonGroup1.add(rbNintendo);
        rbNintendo.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        rbNintendo.setForeground(new java.awt.Color(255, 255, 255));
        rbNintendo.setText("Nintendo");
        rbNintendo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbNintendo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbNintendoMouseClicked(evt);
            }
        });
        rbNintendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNintendoActionPerformed(evt);
            }
        });
        panelFondo.add(rbNintendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, -1));

        buttonGroup1.add(rbXbox);
        rbXbox.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        rbXbox.setForeground(new java.awt.Color(255, 255, 255));
        rbXbox.setText("Xbox");
        rbXbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbXbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbXboxMouseClicked(evt);
            }
        });
        rbXbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbXboxActionPerformed(evt);
            }
        });
        panelFondo.add(rbXbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        buttonGroup1.add(rbPc);
        rbPc.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        rbPc.setForeground(new java.awt.Color(255, 255, 255));
        rbPc.setText("PC");
        rbPc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbPc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbPcMouseClicked(evt);
            }
        });
        rbPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPcActionPerformed(evt);
            }
        });
        panelFondo.add(rbPc, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        lblconsola.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        lblconsola.setForeground(new java.awt.Color(255, 255, 255));
        lblconsola.setText("Consola");
        panelFondo.add(lblconsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, -1, -1));

        jcbConsola.setToolTipText("Selecciona la nueva consola");
        jcbConsola.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbConsola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbConsolaMouseClicked(evt);
            }
        });
        panelFondo.add(jcbConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 390, 30));

        lblfecha.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        lblfecha.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha.setText("<html><p>Fecha</p><p>de salida</p></html>");
        panelFondo.add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, -1));

        tfFecha.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        tfFecha.setForeground(new java.awt.Color(153, 153, 153));
        tfFecha.setText("dd/MM/aaaa");
        tfFecha.setToolTipText("Introduce la nueva fecha de salida con formato <dd/MM/aaaa>");
        tfFecha.setPreferredSize(new java.awt.Dimension(221, 22));
        tfFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfFechaMouseClicked(evt);
            }
        });
        panelFondo.add(tfFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 390, 30));

        lblgenero4.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        lblgenero4.setForeground(new java.awt.Color(255, 255, 255));
        lblgenero4.setText("Valoración");
        panelFondo.add(lblgenero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, -1, -1));

        tfEdicion.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        tfEdicion.setForeground(new java.awt.Color(255, 255, 255));
        tfEdicion.setToolTipText("Introduce el tipo de edición del juego");
        tfEdicion.setPreferredSize(new java.awt.Dimension(221, 22));
        tfEdicion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfEdicionMouseClicked(evt);
            }
        });
        panelFondo.add(tfEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 390, 30));

        lblgenero5.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        lblgenero5.setForeground(new java.awt.Color(255, 255, 255));
        lblgenero5.setText("Edición");
        panelFondo.add(lblgenero5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, -1, -1));

        jsValoracion.setMaximum(4);
        jsValoracion.setToolTipText("Puntúa el juego de 1 a 5 estrellas");
        jsValoracion.setValue(2);
        jsValoracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsValoracion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsValoracionStateChanged(evt);
            }
        });
        jsValoracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsValoracionMouseClicked(evt);
            }
        });
        panelFondo.add(jsValoracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 670, 530, -1));

        estrellas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3estrellas.png"))); // NOI18N
        panelFondo.add(estrellas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 630, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(234, 164, 28));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setToolTipText("Vacía todos los campos de texto");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panelFondo.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 710, 134, 50));

        btnModificar.setBackground(new java.awt.Color(234, 164, 28));
        btnModificar.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setToolTipText("Modifica los datos del juego. Debes introducir todos los datos.");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelFondo.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 710, 134, 50));

        btnEliminar.setBackground(new java.awt.Color(234, 164, 28));
        btnEliminar.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setToolTipText("Elimina el juego de la base de datos. Debes introducir su ID en el campo correspondiente");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelFondo.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 710, 134, 50));

        panelRound1.setBackground(new java.awt.Color(234, 164, 28));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        lblGestionar.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblGestionar.setText("GESTIONAR JUEGO");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(lblGestionar)
                .addGap(134, 134, 134))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblGestionar)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panelFondo.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 519, 113));

        lblID.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID");
        panelFondo.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        tfID.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        tfID.setForeground(new java.awt.Color(153, 153, 153));
        tfID.setText("ID del juego a modificar o borrar");
        tfID.setToolTipText("Introduce el Id del juego que deseas borrar o modificar");
        tfID.setPreferredSize(new java.awt.Dimension(221, 22));
        tfID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfIDMouseClicked(evt);
            }
        });
        tfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDActionPerformed(evt);
            }
        });
        panelFondo.add(tfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 390, 30));

        jSeparator1.setForeground(new java.awt.Color(234, 164, 28));
        panelFondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 520, 10));

        lbltitulo2.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lbltitulo2.setForeground(new java.awt.Color(255, 255, 255));
        lbltitulo2.setText("Título");
        panelFondo.add(lbltitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Método para rellenar el combobox al clickar en PlayStation
     * @param evt 
     */
    private void rbPlayStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPlayStationActionPerformed
        /**
         * Vaciar la lista del comboBox
         */
        jcbConsola.removeAllItems();
        /**
         * Rellenar la lista del comboBox
         */
        jcbConsola.addItem("PS 5");
        jcbConsola.addItem("PS 4");
        jcbConsola.addItem("PS 3");
        jcbConsola.addItem("PS 2");
        jcbConsola.addItem("PlayStation");
        jcbConsola.addItem("PS Vita");
        jcbConsola.addItem("PSP");
    }//GEN-LAST:event_rbPlayStationActionPerformed
    /**
     * Método para rellenar el combobox al clickar en Nintendo
     * @param evt 
     */
    private void rbNintendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNintendoActionPerformed
        /**
         * Vaciar la lista del comboBox
         */
        jcbConsola.removeAllItems();
        /**
         * Rellenar la lista del comboBox
         */
        jcbConsola.addItem("Switch");
        jcbConsola.addItem("Wii U");
        jcbConsola.addItem("Wii");
        jcbConsola.addItem("GameCube");
        jcbConsola.addItem("Nintendo 64");
        jcbConsola.addItem("Supernintendo");
        jcbConsola.addItem("NES");
        jcbConsola.addItem("DS/3ds");
        jcbConsola.addItem("GBA");
        jcbConsola.addItem("GBColor");
        jcbConsola.addItem("GameBoy");
    }//GEN-LAST:event_rbNintendoActionPerformed
    /**
     * Método para rellenar el combobox al clickar en XBox
     * @param evt 
     */
    private void rbXboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbXboxActionPerformed
        /**
         * Vaciar la lista del comboBox
         */
        jcbConsola.removeAllItems();
        /**
         * Rellenar la lista del comboBox
         */
        jcbConsola.addItem("Xbox series X-S");
        jcbConsola.addItem("Xbox one");
        jcbConsola.addItem("Xbox 360");
        jcbConsola.addItem("Xbox");
    }//GEN-LAST:event_rbXboxActionPerformed
    /**
     * Método para rellenar el combobox al clickar en PC
     * @param evt 
     */
    private void rbPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPcActionPerformed
        /**
         * Vaciar la lista del comboBox
         */
        jcbConsola.removeAllItems();
        /**
         * Rellenar la lista del comboBox
         */
        jcbConsola.addItem("Steam");
        jcbConsola.addItem("Epic Games");
        jcbConsola.addItem("Origin");
        jcbConsola.addItem("Ubisoft");
        jcbConsola.addItem("Otros");
    }//GEN-LAST:event_rbPcActionPerformed
    /**
     * Método para rellenar las estrellas a partir del slider
     * @param evt 
     */
    private void jsValoracionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsValoracionStateChanged
        /**
         * Rellenar las estrellas en funcion de la valoracion
         */
        switch(jsValoracion.getValue()){
            case 0:
            estrellas.setIcon(new ImageIcon("src/main/java/img/1estrella.png"));
            break;
            case 1:
            estrellas.setIcon(new ImageIcon("src/main/java/img/2estrellas.png"));
            break;
            case 2:
            estrellas.setIcon(new ImageIcon("src/main/java/img/3estrellas.png"));
            break;
            case 3:
            estrellas.setIcon(new ImageIcon("src/main/java/img/4estrellas.png"));
            break;
            case 4:
            estrellas.setIcon(new ImageIcon("src/main/java/img/5estrellas.png"));
            break;
        }
    }//GEN-LAST:event_jsValoracionStateChanged
    /**
     * Método de funcionalidad del botón limpiar
     * @param evt 
     */
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        /**
         * Llamamos al método limpiar
         */
        limpiar();       
    }//GEN-LAST:event_btnLimpiarActionPerformed

  
    /**
     * Método de funcionalidad del botón modificar
     * @param evt 
     */
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        boolean idValido=true;
        boolean correcto=true;
        /**
         * Comprobamos que haya un id en el textfield
         */
        if(tfID.getText().isEmpty() || tfID.getText().equals("ID del juego a modificar o borrar")){
            JOptionPane.showMessageDialog(null, "ERROR, Debe introducir el ID del juego que desea eliminar","Error", JOptionPane.ERROR_MESSAGE);
        }else {
            try{
              idJuego=Integer.parseInt(tfID.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "ERROR, Debe introducir el ID Válido","Error", JOptionPane.ERROR_MESSAGE);
                idValido=false;
            }
            if(idValido){
                /**
                 * Comprobamos que el resto de campos sean válidos
                 */
                try{
                    Videojuegos v=new Videojuegos();
                    if (tfTitulo.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "ERROR, Introduzca el nuevo título","Error", JOptionPane.ERROR_MESSAGE);
                    } else if (tfGenero.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "ERROR, Introduzca el nuevo género","Error", JOptionPane.ERROR_MESSAGE);
                    } else if (tfFecha.getText().isEmpty()){
                        JOptionPane.showMessageDialog(null, "ERROR, Formato de fecha incorrecto","Error", JOptionPane.ERROR_MESSAGE);
                    } else if (tfEdicion.getText().isEmpty()){
                        JOptionPane.showMessageDialog(null, "ERROR, Introduzca la nueva edición","Error", JOptionPane.ERROR_MESSAGE);
                    } else if(!rbNintendo.isSelected() && !rbPlayStation.isSelected() && !rbXbox.isSelected() && !rbPc.isSelected()){
                        JOptionPane.showMessageDialog(null, "ERROR, Seleccione una plataforma","Error", JOptionPane.ERROR_MESSAGE);
                    } else if(jcbConsola.getSelectedItem()==null){
                        JOptionPane.showMessageDialog(null, "ERROR, Seleccione una consola","Error", JOptionPane.ERROR_MESSAGE);
                    } else {

                        v.setTitulo(tfTitulo.getText());
                        v.setGenero(tfGenero.getText());

                        /**
                         * Parsear la fecha si el campo no está vacío
                         */
                        if(!tfFecha.getText().isEmpty()){
                            SimpleDateFormat fecha=new SimpleDateFormat("dd/MM/yyyy");
                            try {
                                //v.setFechaSalida((Date) fecha.parse(tfFecha.getText()));
                                java.util.Date utilDate = fecha.parse(tfFecha.getText());
                                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                                v.setFechaSalida(sqlDate);
                            } catch (ParseException ex) {
                                Logger.getLogger(PanelRegistrar.class.getName()).log(Level.SEVERE, null, ex);
                                //System.err.println("Error de formato fecha");
                                JOptionPane.showMessageDialog(null, "ERROR, Formato de fecha incorrecto <dd/MM/yyyy>","Error", JOptionPane.ERROR_MESSAGE);
                                /**
                                 * ponemos la bandera a false para evitar la inserción de un formato de fecha incorrecto
                                 */
                                correcto=false;
                            }
                        }
                        v.setEdicion(tfEdicion.getText());
                        /**
                         * Obetener la plataforma y la consola
                         */
                        if(rbNintendo.isSelected()){
                            v.setPlataforma("Nintendo");
                            String consola=(String)jcbConsola.getSelectedItem();
                            v.setConsola(consola);
                        }else if(rbPlayStation.isSelected()){
                            v.setPlataforma("PlayStation");
                            String consola=(String)jcbConsola.getSelectedItem();
                            v.setConsola(consola);
                        }else if(rbXbox.isSelected()){
                            v.setPlataforma("XBox");
                            String consola=(String)jcbConsola.getSelectedItem();
                            v.setConsola(consola);
                        }
                        else if(rbPc.isSelected()){
                            v.setPlataforma("PC");
                            String consola=(String)jcbConsola.getSelectedItem();
                            v.setConsola(consola);
                        }

                        v.setValoracion(jsValoracion.getValue());
                        /**
                         * Si todo es correcto procedemos a modificar el juego
                         */
                        if(correcto){
                            /**
                             * Llamamos al método modificarJuego
                             */
                            if(HibernateUtil.modificarJuego(idJuego,v)){
                                JOptionPane.showMessageDialog(null, "Videojuego modificado correctamente");
                                /**
                                 * Llamamos al método limpiar para resetear los textFields
                                 */
                                limpiar();
                            }else{
                                JOptionPane.showMessageDialog(null, "ERROR,no se ha podido modificar el videojuego","Error", JOptionPane.ERROR_MESSAGE);
                            }                           
                        }
                    }
                }catch(PropertyValueException e){
                    JOptionPane.showMessageDialog(null, "ERROR,no se ha podido añadir el videojuego a su colección","Error", JOptionPane.ERROR_MESSAGE);
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "ERROR, Debe introducir el ID Válido","Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        Videojuegos v=new Videojuegos();
    }//GEN-LAST:event_btnModificarActionPerformed
    /**
     * Método de funcionalidad del botón eliminar
     * @param evt 
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        boolean idValido=true;
        /**
         * Comprobamos que haya un id en el textfield
         */
        if(tfID.getText().isEmpty() || tfID.getText().equals("ID del juego a modificar o borrar")){
            JOptionPane.showMessageDialog(null, "ERROR, Debe introducir el ID del juego que desea eliminar","Error", JOptionPane.ERROR_MESSAGE);
        }else {
            try{
              idJuego=Integer.parseInt(tfID.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "ERROR, Debe introducir el ID Válido","Error", JOptionPane.ERROR_MESSAGE);
                idValido=false;
            }
            if(idValido){
                /**
                 * Mostramos el cuadro de diálogo para confirmar el borrado
                 */
                confirmarBorrado();
            }else{
                JOptionPane.showMessageDialog(null, "ERROR, Debe introducir el ID Válido","Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    /**
     * Método para rellenar la fecha y el id al clickar en título
     * @param evt 
     */
    private void tfTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTituloMouseClicked
        //Si la fecha está vacía rellenarla por defecto
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
        
        //Si el id está vacía rellenarlo por defecto
        if(tfID.getText().equals("")){
            tfID.setText("ID del juego a modificar o borrar");
            tfID.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_tfTituloMouseClicked
    /**
     * Método para rellenar la fecha y el id al clickar en género
     * @param evt 
     */
    private void tfGeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfGeneroMouseClicked
        /**
         * Si la fecha está vacía rellenarla por defecto
         */ 
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
        //Si el id está vacía rellenarlo por defecto
        if(tfID.getText().equals("")){
            tfID.setText("ID del juego a modificar o borrar");
            tfID.setForeground(new Color(153,153,153));
        }

    }//GEN-LAST:event_tfGeneroMouseClicked
    /**
     * Método para rellenar la fecha y el id al clickar en Nintendo
     * @param evt 
     */
    private void rbNintendoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbNintendoMouseClicked
        /**
         * Si la fecha está vacía rellenarla por defecto
         */ 
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
        /**
         * Si el id está vacía rellenarlo por defecto
         */
        if(tfID.getText().equals("")){
            tfID.setText("ID del juego a modificar o borrar");
        }
        tfID.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_rbNintendoMouseClicked
    /**
     * Método para rellenar la fecha y el id al clickar en PlayStation
     * @param evt 
     */
    private void rbPlayStationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbPlayStationMouseClicked
       //Si la fecha está vacía rellenarla por defecto
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
        //Si el id está vacía rellenarlo por defecto
        if(tfID.getText().equals("")){
            tfID.setText("ID del juego a modificar o borrar");
            tfID.setForeground(new Color(153,153,153));
        }

    }//GEN-LAST:event_rbPlayStationMouseClicked
    /**
     * Método para rellenar la fecha y el id al clickar en XBox
     * @param evt 
     */
    private void rbXboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbXboxMouseClicked
       //Si la fecha está vacía rellenarla por defecto
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
        //Si el id está vacía rellenarlo por defecto
        if(tfID.getText().equals("")){
            tfID.setText("ID del juego a modificar o borrar");
            tfID.setForeground(new Color(153,153,153));
        }

    }//GEN-LAST:event_rbXboxMouseClicked
    /**
     * Método para rellenar la fecha y el id al clickar en PC
     * @param evt 
     */
    private void rbPcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbPcMouseClicked
        //Si la fecha está vacía rellenarla por defecto
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
        //Si el id está vacía rellenarlo por defecto
        if(tfID.getText().equals("")){
            tfID.setText("ID del juego a modificar o borrar");
            tfID.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_rbPcMouseClicked
    /**
     * Método para rellenar la fecha y el id al clickar en Consola
     * @param evt 
     */
    private void jcbConsolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbConsolaMouseClicked
        //Si la fecha está vacía rellenarla por defecto
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
        //Si el id está vacía rellenarlo por defecto
        if(tfID.getText().equals("")){
            tfID.setText("ID del juego a modificar o borrar");
            tfID.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_jcbConsolaMouseClicked
    /**
     * Método para rellenar la fecha y el id al clickar en Edición
     * @param evt 
     */
    private void tfEdicionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEdicionMouseClicked
        //Si la fecha está vacía rellenarla por defecto
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
        //Si el id está vacía rellenarlo por defecto
        if(tfID.getText().equals("")){
            tfID.setText("ID del juego a modificar o borrar");
            tfID.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_tfEdicionMouseClicked
    /**
     * Método para rellenar la fecha y el id al clickar en Valoración
     * @param evt 
     */
    private void jsValoracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsValoracionMouseClicked
        //Si la fecha está vacía rellenarla por defecto
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
        //Si el id está vacía rellenarlo por defecto
        if(tfID.getText().equals("")){
            tfID.setText("ID del juego a modificar o borrar");
            tfID.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_jsValoracionMouseClicked
    /**
     * Método para vaciar la fecha y rellenar el id al clickar en fecha
     * @param evt 
     */
    private void tfFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfFechaMouseClicked
        if(tfFecha.getText().equals("dd/MM/aaaa")){
            tfFecha.setText("");
            tfFecha.setForeground(Color.WHITE);
        }
        //Si el id está vacía rellenarlo por defecto
        if(tfID.getText().equals("")){
            tfID.setText("ID del juego a modificar o borrar");
            tfID.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_tfFechaMouseClicked
/**
     * Método para rellenar la fecha y vaciar el id al clickar en id
     * @param evt 
     */
    private void tfIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfIDMouseClicked
        //Vaciar el textField al clickar en él
        if(tfID.getText().equals("ID del juego a modificar o borrar")){
            tfID.setText("");
            tfID.setForeground(Color.WHITE);
        }
        
        //Si la fecha está vacía rellenarla por defecto
        if(tfFecha.getText().equals("")){
            tfFecha.setText("dd/MM/aaaa");
            tfFecha.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_tfIDMouseClicked

    private void tfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel estrellas;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jcbConsola;
    private javax.swing.JSlider jsValoracion;
    private javax.swing.JLabel lblGestionar;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblconsola;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblgenero1;
    private javax.swing.JLabel lblgenero4;
    private javax.swing.JLabel lblgenero5;
    private javax.swing.JLabel lblplataforma;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lbltitulo2;
    private javax.swing.JPanel panelFondo;
    private vista.PanelRound panelRound1;
    private javax.swing.JRadioButton rbNintendo;
    private javax.swing.JRadioButton rbPc;
    private javax.swing.JRadioButton rbPlayStation;
    private javax.swing.JRadioButton rbXbox;
    private javax.swing.JTextField tfEdicion;
    private javax.swing.JTextField tfFecha;
    private javax.swing.JTextField tfGenero;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfTitulo;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Método para limpiar los textFields
     */
    public void limpiar(){
        /**
         * Vaciar todos los campos
         */
        tfTitulo.setText("");
        tfGenero.setText("");
        tfFecha.setText("dd/MM/aaaa");
        tfFecha.setForeground(new Color(153,153,153));
        tfEdicion.setText("");
        rbNintendo.setSelected(false);
        rbPlayStation.setSelected(false);
        rbXbox.setSelected(false);
        rbPc.setSelected(false);
        jsValoracion.setValue(2);
        tfID.setText("ID del juego a modificar o borrar");
        tfID.setForeground(new Color(153,153,153));
    }
    /**
     * Método para crear ventana de diálogo para confirmar el borrado de un juego de la colección de un usuario
     */
    public void confirmarBorrado(){
        int opcion = JOptionPane.showConfirmDialog( null,"¿Seguro que deseas borrar el juego?","Confirmar Borrado",JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            /**
            * Llamamos al método borrarJuego, si nos da true el juego se habrá eliminado correctamente
            */
            if(HibernateUtil.borrarJuegoColeccion(idJuego)>0){
                JOptionPane.showMessageDialog(null, "El videojuego ha sido eliminado de su colección");
                /**
                 * Le damos la opción al usuario de eliminar el juego completamente de la base de datos
                 */
                confirmarBorradoTotal();
                /**
                 * limpiamos los textfields
                 */
                limpiar();
            }else{
                JOptionPane.showMessageDialog(null, "ERROR, No se ha podido elimiar el juego","Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Se ha cancelado la eliminación del juego");
        }
    }
    /**
     * Método para crear ventana de diálogo para confirmar el borrado de un juego de la base de datos
     */
    public void confirmarBorradoTotal(){
        int opcion = JOptionPane.showConfirmDialog( null,"¿Desea borrar también el juego completamente de la base de datos?","Confirmar Borrado Total",JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            if(HibernateUtil.borrarJuego(idJuego)){
                JOptionPane.showMessageDialog(null, "El videojuego ha sido eliminado completamente");
            }else{
                JOptionPane.showMessageDialog(null, "ERROR, No se ha podido elimiar el juego de la base de datos","Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Se ha cancelado la eliminación del juego");
        }
    }

}
