/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.HibernateUtil;
import controlador.PasswordUtil;
import java.awt.Color;
import javax.swing.JOptionPane;
import model.Usuarios;

/**
 *
 * @author lonch
 */
public class VentanaRecuperar extends javax.swing.JFrame {

    //Variables para mover la ventana
    int xMouse,yMouse;
    //Variables de los controladores
    HibernateUtil hibernate;
    PasswordUtil pwdUtil;
    
    public VentanaRecuperar() {
        initComponents();
        btnEnvio.setForeground(Color.BLACK);
        
        //Conecta a la base de datos
        hibernate=new HibernateUtil();
        hibernate.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelFondoGris = new javax.swing.JPanel();
        tfCorreoElectronico = new javax.swing.JTextField();
        btnEnvio = new javax.swing.JButton();
        lbRecuperar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbCerrarSesion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfRecUsuario = new javax.swing.JTextField();
        xCerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logoGGpeque = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelFondo.setBackground(new java.awt.Color(0, 0, 0));
        panelFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelFondoMouseDragged(evt);
            }
        });
        panelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelFondoMousePressed(evt);
            }
        });
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondoGris.setBackground(new java.awt.Color(37, 34, 28));
        panelFondoGris.setMinimumSize(new java.awt.Dimension(350, 519));
        panelFondoGris.setPreferredSize(new java.awt.Dimension(358, 519));
        panelFondoGris.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfCorreoElectronico.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        tfCorreoElectronico.setForeground(new java.awt.Color(153, 153, 153));
        tfCorreoElectronico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCorreoElectronico.setMinimumSize(new java.awt.Dimension(64, 22));
        tfCorreoElectronico.setPreferredSize(new java.awt.Dimension(257, 22));
        tfCorreoElectronico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfCorreoElectronicoMousePressed(evt);
            }
        });
        tfCorreoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCorreoElectronicoActionPerformed(evt);
            }
        });
        panelFondoGris.add(tfCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 30));

        btnEnvio.setBackground(new java.awt.Color(244, 150, 40));
        btnEnvio.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        btnEnvio.setText("Enviar");
        btnEnvio.setPreferredSize(new java.awt.Dimension(192, 40));
        btnEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvioActionPerformed(evt);
            }
        });
        panelFondoGris.add(btnEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 259, -1, 41));

        lbRecuperar.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        lbRecuperar.setForeground(new java.awt.Color(244, 150, 40));
        lbRecuperar.setText("Cambiar contraseña");
        lbRecuperar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbRecuperarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbRecuperarMouseExited(evt);
            }
        });
        panelFondoGris.add(lbRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, 20));

        jSeparator1.setForeground(new java.awt.Color(244, 150, 40));
        panelFondoGris.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 364, 127, 10));

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("O");
        panelFondoGris.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 358, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(244, 150, 40));
        panelFondoGris.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 364, 127, 10));

        lbCerrarSesion.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        lbCerrarSesion.setForeground(new java.awt.Color(244, 150, 40));
        lbCerrarSesion.setText("Cerrar sesión");
        lbCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCerrarSesionMouseExited(evt);
            }
        });
        panelFondoGris.add(lbCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, 20));

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Correo electrónico");
        panelFondoGris.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre de usuario");
        panelFondoGris.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        tfRecUsuario.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        tfRecUsuario.setForeground(new java.awt.Color(153, 153, 153));
        tfRecUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfRecUsuario.setMinimumSize(new java.awt.Dimension(64, 22));
        tfRecUsuario.setPreferredSize(new java.awt.Dimension(257, 22));
        tfRecUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfRecUsuarioMousePressed(evt);
            }
        });
        tfRecUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRecUsuarioActionPerformed(evt);
            }
        });
        panelFondoGris.add(tfRecUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 30));

        panelFondo.add(panelFondoGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 377, 480));

        xCerrar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        xCerrar.setForeground(new java.awt.Color(255, 255, 255));
        xCerrar.setText("x");
        xCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xCerrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                xCerrarMousePressed(evt);
            }
        });
        panelFondo.add(xCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 6, -1, 22));

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html><p>RECUPERAR</p><p>CONTRASEÑA</p></html>");
        panelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        logoGGpeque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoGGpeque.png"))); // NOI18N
        panelFondo.add(logoGGpeque, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 51, 140, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCorreoElectronicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCorreoElectronicoMousePressed
        //Quitar el texto Usuario al entrar
        if(tfCorreoElectronico.getText().equals("Usuario")){
            tfCorreoElectronico.setText("");
            tfCorreoElectronico.setForeground(Color.white);
        }
        //Si el password está vacío escribir los asteriscos en él
        /*if(String.valueOf(jPFRepetirPassword.getPassword()).isEmpty()){
            jPFRepetirPassword.setText("********");
            jPFRepetirPassword.setForeground(Color.gray);
        }*/
    }//GEN-LAST:event_tfCorreoElectronicoMousePressed

    private void tfCorreoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCorreoElectronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCorreoElectronicoActionPerformed

    private void btnEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvioActionPerformed
        //Comprobar email en la base de datos
        Usuarios usuario=new Usuarios();
        usuario.setUsername(tfRecUsuario.getText());
        usuario.setEmail(tfCorreoElectronico.getText());

        if(hibernate.comprobarMail(usuario).get(0).getUsername().equals(tfRecUsuario.getText()) && hibernate.comprobarMail(usuario).get(0).getEmail().equals(tfCorreoElectronico.getText()) ){
            //Generar contraseña nueva
            
            
            //Enviar mail al usuario
            
        }else{
            JOptionPane.showMessageDialog(null, "ERROR, No se ha encontrado ningún usuario con ese correro electrónico","Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEnvioActionPerformed

    private void lbRecuperarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRecuperarMouseEntered
        //Cambiar color al entrar en recuperar contraseña
        lbRecuperar.setForeground(Color.white);
    }//GEN-LAST:event_lbRecuperarMouseEntered

    private void lbRecuperarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRecuperarMouseExited
        //Cambiar color al salir de recuperar contraseña
        lbRecuperar.setForeground(new Color(244,150,40));
    }//GEN-LAST:event_lbRecuperarMouseExited

    private void lbCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCerrarSesionMouseClicked
        //Abrimos la ventana de registro de usuario
    }//GEN-LAST:event_lbCerrarSesionMouseClicked

    private void lbCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCerrarSesionMouseEntered
        //Cambiar color al entrar en registrarse
        lbCerrarSesion.setForeground(Color.white);
    }//GEN-LAST:event_lbCerrarSesionMouseEntered

    private void lbCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCerrarSesionMouseExited
        //Cambiar color al salir de registrarse
        lbCerrarSesion.setForeground(new Color(244,150,40));
    }//GEN-LAST:event_lbCerrarSesionMouseExited

    private void tfRecUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfRecUsuarioMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfRecUsuarioMousePressed

    private void tfRecUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRecUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRecUsuarioActionPerformed

    private void xCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xCerrarMouseClicked
        VentanaLogin ventanaLogin=new VentanaLogin();
        ventanaLogin.setVisible(true);
        //Cerrar ventana
        dispose();

    }//GEN-LAST:event_xCerrarMouseClicked

    private void xCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xCerrarMouseEntered
        //Cambiar color al entrar
        xCerrar.setForeground(new Color(244,150,40));
    }//GEN-LAST:event_xCerrarMouseEntered

    private void xCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xCerrarMouseExited
        //Cambiar a blanco al salir
        xCerrar.setForeground(Color.white);
    }//GEN-LAST:event_xCerrarMouseExited

    private void xCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xCerrarMousePressed
        //Cambiar color al pulsar
        xCerrar.setForeground(Color.red);
    }//GEN-LAST:event_xCerrarMousePressed

    private void panelFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFondoMouseDragged
        // Mover la ventana
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_panelFondoMouseDragged

    private void panelFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFondoMousePressed
        // Obtener x e y para mover la ventana
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_panelFondoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRecuperar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRecuperar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRecuperar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRecuperar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRecuperar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnvio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbCerrarSesion;
    private javax.swing.JLabel lbRecuperar;
    private javax.swing.JLabel logoGGpeque;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelFondoGris;
    private javax.swing.JTextField tfCorreoElectronico;
    private javax.swing.JTextField tfRecUsuario;
    private javax.swing.JLabel xCerrar;
    // End of variables declaration//GEN-END:variables
}
