/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialDarkerIJTheme;
import java.awt.Color;

/**
 *
 * @author Javier Marcos Cobaleda
 */
public class VentanaLogin extends javax.swing.JFrame {

    //Variables para mover la ventana
    int xMouse,yMouse;
    
    public VentanaLogin() {
        initComponents();
        //Redonder componentes
        btnIniciarSesion.putClientProperty("FlatLaf.style","arc: 20");
        tfusuario.putClientProperty("FlatLaf.style","arc: 20");
        jPFPassword.putClientProperty("FlatLaf.style","arc: 20");
        //jPFPassword.putClientProperty("FlatLaf.colorClass",Color.white);
        btnIniciarSesion.setForeground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelFondoGris = new javax.swing.JPanel();
        tfusuario = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        jPFPassword = new javax.swing.JPasswordField();
        lbRecuperar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbRegistrarse = new javax.swing.JLabel();
        xCerrar = new javax.swing.JLabel();
        logoGGpeque = new javax.swing.JLabel();
        imagenLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelFondo.setBackground(new java.awt.Color(0, 0, 0));
        panelFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelFondoMouseDragged(evt);
            }
        });
        panelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelFondoMousePressed(evt);
            }
        });
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondoGris.setBackground(new java.awt.Color(37, 34, 28));
        panelFondoGris.setMinimumSize(new java.awt.Dimension(350, 519));
        panelFondoGris.setPreferredSize(new java.awt.Dimension(358, 519));
        panelFondoGris.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfusuario.setForeground(new java.awt.Color(153, 153, 153));
        tfusuario.setText("Usuario");
        tfusuario.setPreferredSize(new java.awt.Dimension(257, 54));
        tfusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfusuarioMousePressed(evt);
            }
        });
        panelFondoGris.add(tfusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        btnIniciarSesion.setBackground(new java.awt.Color(244, 150, 40));
        btnIniciarSesion.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.setPreferredSize(new java.awt.Dimension(192, 40));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        panelFondoGris.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 259, -1, 41));

        jPFPassword.setText("jPasswordField1");
        jPFPassword.setPreferredSize(new java.awt.Dimension(257, 54));
        jPFPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPFPasswordMousePressed(evt);
            }
        });
        panelFondoGris.add(jPFPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        lbRecuperar.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        lbRecuperar.setForeground(new java.awt.Color(244, 150, 40));
        lbRecuperar.setText("Recuperar contraseña");
        lbRecuperar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbRecuperarMouseEntered(evt);
            }
        });
        panelFondoGris.add(lbRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(244, 150, 40));
        panelFondoGris.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 364, 127, 10));

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("O");
        panelFondoGris.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 358, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(244, 150, 40));
        panelFondoGris.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 364, 127, 10));

        lbRegistrarse.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        lbRegistrarse.setForeground(new java.awt.Color(244, 150, 40));
        lbRegistrarse.setText("Registrarse");
        panelFondoGris.add(lbRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        panelFondo.add(panelFondoGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 377, 480));

        xCerrar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        xCerrar.setForeground(new java.awt.Color(255, 255, 255));
        xCerrar.setText("x");
        xCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xCerrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                xCerrarMousePressed(evt);
            }
        });
        panelFondo.add(xCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 6, -1, 22));

        logoGGpeque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoGGpeque.png"))); // NOI18N
        panelFondo.add(logoGGpeque, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        imagenLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGGIN.png"))); // NOI18N
        panelFondo.add(imagenLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xCerrarMouseClicked
        //Cerrar ventana
        System.exit(0);
    }//GEN-LAST:event_xCerrarMouseClicked

    private void xCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xCerrarMouseEntered
        //Cambiar color al entrar
        xCerrar.setForeground(new Color(244,150,40));
    }//GEN-LAST:event_xCerrarMouseEntered

    private void xCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xCerrarMouseExited
        //Cambiar a blanco al salir
        xCerrar.setForeground(Color.white);
    }//GEN-LAST:event_xCerrarMouseExited

    private void xCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xCerrarMousePressed
        //Cambiar color al pulsar
        xCerrar.setForeground(Color.red);
    }//GEN-LAST:event_xCerrarMousePressed

    private void panelFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFondoMousePressed
        // Obtener x e y para mover la ventana
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_panelFondoMousePressed

    private void panelFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFondoMouseDragged
        // Mover la ventana
       int x=evt.getXOnScreen();
       int y=evt.getYOnScreen();
       this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_panelFondoMouseDragged

    private void tfusuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfusuarioMousePressed
        // TODO add your handling code here:
        if(tfusuario.getText().equals("Usuario")){
            tfusuario.setText("");
            tfusuario.setForeground(Color.white);
        }
        
        if(String.valueOf(jPFPassword.getPassword()).isEmpty()){
            jPFPassword.setText("********");
            jPFPassword.setForeground(Color.gray);
        }
                               
    }//GEN-LAST:event_tfusuarioMousePressed

    private void jPFPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPFPasswordMousePressed
        // TODO add your handling code here:
        if(String.valueOf(jPFPassword.getPassword()).equals("********")){
            jPFPassword.setText("");
            jPFPassword.setForeground(Color.white);
        }
        
        if(tfusuario.getText().isEmpty()){
            tfusuario.setText("Usuario");
            tfusuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jPFPasswordMousePressed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void lbRecuperarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRecuperarMouseEntered
         // TODO add your handling code here:
         lbRecuperar.setForeground(Color.white);
    }//GEN-LAST:event_lbRecuperarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Flatlaf
        FlatMaterialDarkerIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel imagenLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPFPassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbRecuperar;
    private javax.swing.JLabel lbRegistrarse;
    private javax.swing.JLabel logoGGpeque;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelFondoGris;
    private javax.swing.JTextField tfusuario;
    private javax.swing.JLabel xCerrar;
    // End of variables declaration//GEN-END:variables
}
